// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMoviesApp.Infrastructure.Data;

#nullable disable

namespace MyMoviesApp.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MyMoviesAppContext))]
    partial class MyMoviesAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("MyMoviesApp.Infrastructure.Data.Models.DigitalRetailer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DigitalRetailers");
                });

            modelBuilder.Entity("MyMoviesApp.Infrastructure.Data.Models.MovieFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MovieFormats");
                });

            modelBuilder.Entity("MyMoviesApp.Infrastructure.Data.Models.UserDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyMoviesApp.Infrastructure.Data.Models.UserMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TmdbId")
                        .IsUnique();

                    b.ToTable("UserMovies");
                });

            modelBuilder.Entity("MyMoviesApp.Infrastructure.Data.Models.UserMovieDigitalRetailer", b =>
                {
                    b.Property<int>("UserMovieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DigitalRetailerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserMovieId", "DigitalRetailerId");

                    b.HasIndex("DigitalRetailerId");

                    b.ToTable("UserMovieDigitalRetailers");
                });

            modelBuilder.Entity("MyMoviesApp.Infrastructure.Data.Models.UserMovieFormat", b =>
                {
                    b.Property<int>("UserMovieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieFormatId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserMovieId", "MovieFormatId");

                    b.HasIndex("MovieFormatId");

                    b.ToTable("UserMovieFormats");
                });

            modelBuilder.Entity("MyMoviesApp.Infrastructure.Data.Models.UserMovie", b =>
                {
                    b.HasOne("MyMoviesApp.Infrastructure.Data.Models.UserDb", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyMoviesApp.Infrastructure.Data.Models.UserMovieDigitalRetailer", b =>
                {
                    b.HasOne("MyMoviesApp.Infrastructure.Data.Models.DigitalRetailer", null)
                        .WithMany()
                        .HasForeignKey("DigitalRetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMoviesApp.Infrastructure.Data.Models.UserMovie", null)
                        .WithMany("UserMovieDigitalRetailers")
                        .HasForeignKey("UserMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyMoviesApp.Infrastructure.Data.Models.UserMovieFormat", b =>
                {
                    b.HasOne("MyMoviesApp.Infrastructure.Data.Models.MovieFormat", null)
                        .WithMany()
                        .HasForeignKey("MovieFormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMoviesApp.Infrastructure.Data.Models.UserMovie", null)
                        .WithMany("UserMovieFormats")
                        .HasForeignKey("UserMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyMoviesApp.Infrastructure.Data.Models.UserMovie", b =>
                {
                    b.Navigation("UserMovieDigitalRetailers");

                    b.Navigation("UserMovieFormats");
                });
#pragma warning restore 612, 618
        }
    }
}
